---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-nodejs-connection
type: Opaque
stringData:
  MONGODB_REPLICA_HOSTNAMES: example-mongo-0.example-mongo-svc.mongodb.svc.cluster.local:27017,example-mongo-1.example-mongo-svc.mongodb.svc.cluster.local:27017,example-mongo-2.example-mongo-svc.mongodb.svc.cluster.local:27017
  MONGODB_REPLICA_SET: example-mongo
  MONGODB_DBNAME: example
  MONGODB_USER: mongodb-example-user
  MONGODB_PASSWORD: password
  MONGODB_AUTH_DBNAME: example
  # username and password created from deployment/3-mongodb-user.yaml
  MONGODB_CA_PATH: /etc/tls-mongo/tls.crt
  # MONGODB_CA_PATH is the location of the volumeMounts for the custom CA
---
apiVersion: v1
kind: Service
metadata:
  name: example-node-service
  labels:
    app: example-node
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: example-node
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-node-deployment
  labels:
    app: example-node
spec:
  selector:
    matchLabels:
      app: example-node
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: example-node
    spec:
      containers:
        - image: anthonyamanse/example-nodejs-mongodb:1.0
          imagePullPolicy: Always
          name: example-node
          env:
            - name: PORT
              value: '8080'
          envFrom:
            - secretRef:
                name: mongodb-nodejs-connection
                # secret created above
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: mongo-ca
              mountPath: "/etc/tls-mongo"
              readOnly: true
      volumes:
        - name: mongo-ca
          secret:
            # the custom CA that was used to create mongodb's certificates in previous steps
            # (cert-manager/issuer.yaml)
            secretName: ca-key-pair
            items:
            - key: tls.crt
              path: tls.crt

---
apiVersion: v1
kind: Route
metadata:
  name: example-node-service
spec:
  to:
    kind: Service
    name: example-node-service